--- #YAML:1.0
name:                XML-RSS
version:             1.33
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    DateTime:                      0
    DateTime::Format::Mail:        0
    DateTime::Format::W3CDTF:      0
    HTML::Entities:                0
    Test::Manifest:                0.9
    Test::More:                    0
    XML::Parser:                   2.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
