---
name: XML-RSS
version: 1.38
author:
  - 'Original code: Jonathan Eisenzopf <eisen@pobox.com>'
  - |-
    Further changes: Rael Dornfest <rael@oreilly.com>, Ask Bjoern Hansen 
    <ask@develooper.com>
  - 'Currently: Shlomi Fish <shlomif@cpan.org>'
abstract: creates and updates RSS files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  HTML::Entities: 0
  XML::Parser: 2.23
  perl: 5.006
build_requires:
  Test::Manifest: 0.9
  Test::More: 0
provides:
  XML::RSS:
    file: lib/XML/RSS.pm
    version: 1.38
  XML::RSS::Private::Output::Base:
    file: lib/XML/RSS/Private/Output/Base.pm
  XML::RSS::Private::Output::Roles::ImageDims:
    file: lib/XML/RSS/Private/Output/Roles/ImageDims.pm
  XML::RSS::Private::Output::Roles::ModulesElems:
    file: lib/XML/RSS/Private/Output/Roles/ModulesElems.pm
  XML::RSS::Private::Output::V0_9:
    file: lib/XML/RSS/Private/Output/V0_9.pm
  XML::RSS::Private::Output::V0_91:
    file: lib/XML/RSS/Private/Output/V0_91.pm
  XML::RSS::Private::Output::V1_0:
    file: lib/XML/RSS/Private/Output/V1_0.pm
  XML::RSS::Private::Output::V2_0:
    file: lib/XML/RSS/Private/Output/V2_0.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
